version: '3.3'
services:
  multitenancy-rest-service:
    build: 
      context: ./multitenancy-rest-service
      dockerfile: Dockerfile
    container_name: 'multitenancy-rest-service'
    volumes:
      - ./multitenancy-rest-service:/usr/src/app
    networks:
      - internal
    ports:
      - '5000:5000'

  tenant-registration:
    build: ./tenant-registration
    container_name: 'tenant-registration'
    volumes:
      - ./tenant-registration:/usr/src/app
    networks:
      - internal
    ports:
      - '8875:8875'

  tenant-master-service:
    build: ./tenant-master-service
    container_name: 'tenant-master-service'
    volumes:
      - ./tenant-master-service:/usr/src/app
    networks:
      - internal
    ports:
      - '8847:8847'

  tenant-provisioning:
    build: ./tenant-provisioning
    container_name: 'tenant-provisioning'
    volumes:
      - ./tenant-provisioning:/usr/src/app
    networks:
      - internal
    ports:
      - '8878:8878'

  tenant-config-service:
    build:
      context: ./tenant-config-service
      dockerfile: Dockerfile
    container_name: 'tenant-config-service'
    volumes:
      - ./tenant-config-service:/usr/src/app
    networks:
      - internal
    ports:
      - '8848:8848'
networks:
  internal:
volumes:
  mysql: