version: '3.3'
services:
  database:
    image: 'mysql:8'
    cap_add:
      - SYS_NICE
    container_name: 'rest_api_mysql'
    hostname: 'rest_api_mysql'
    networks:
        - internal
    ports:
        - '127.0.0.1:3306:3306'
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - mysql:/var/lib/mysql
    environment:
        MYSQL_EXPOSE_PORT: '3306'
        MYSQL_ROOT_PASSWORD: 'root'
      #  MYSQL_USER: 'root'
      #  MYSQL_ROOT_USER: 'root'
      #  MYSQL_PASSWORD: 'root'

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    container_name: 'node_rest_keycloak'
    networks:
      - internal
    ports:
        - '8080:8080'
    environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: adminPassword@1

  mail-server:
    image: mailhog/mailhog
    container_name: 'node_rest_mail'
    networks:
      - internal
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
  

  multitenancy-rest-service:
    depends_on:
      - database
      - tenant-config-service
      - tenant-registration
      - keycloak
    env_file:
      - ./multitenancy-rest-service/config/.env

  tenant-registration:
    depends_on:
      - database
      - tenant-master-service
    env_file:
      - ./config/.env
      - ./tenant-registration/config/.env

  tenant-master-service:
    depends_on:
      - tenant-provisioning
      - tenant-config-service
    env_file:
      - ./tenant-master-service/config/.env

  tenant-provisioning:
    depends_on:
      - database
    env_file:
      - ./config/.env
      - ./tenant-provisioning/config/.env

  tenant-config-service:
    depends_on:
      - database
    env_file:
      - ./config/.env
      - ./tenant-config-service/config/.env

  