name: CI
on:
  push:
    paths:
      - 'multitenacy-rest-service/*'
      - 'tenant-config-service/*'
      - 'tenant-provisioning/*'
      - 'tenant-registration/*'
    branches:
      - main
      - dev
      - release-*
  pull_request:
    paths:
      - 'multitenacy-rest-service/*'
      - 'tenant-config-service/*'
      - 'tenant-provisioning/*'
      - 'tenant-registration/*'
    types: [opened, synchronize, reopened]
    branches:
      - main
      - dev
      - release-*
jobs:
  CI:
    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x]
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up nodejs version ${{ matrix.node-version }}
      uses: actions/setup-node@v2.5.1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package
      run: npm install
    - name: Linter
      run:  npm run lint
    - name: Build
      run: npm run build --if-present
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}